FROM nginx:alpine
# Copia as configurações do Nginx (opcional, se quiser customizar rotas)
# COPY ./nginx.conf /etc/nginx/conf.d/default.conf
# Copia os arquivos HTML convertidos
COPY ./html /usr/share/nginx/html
EXPOSE 80